# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: LTID - Lycée Technique Industriel Maurice Delafosse
collections:
  posts:
    title: Posts
    output: true
  domaines:
    title: domaines
    output: true
  programmes:
    title: programmes
    output: true
  commentaires:
    title: commentaires
    output: true
  partenaires:
    title: partenaires
    output: true
adresse: Rocade Fann Bel Air – BP 4004 Dakar, Sénégal
email: info@ltid.com
tel: (+221) 33 822 21 16
description: >- # this means to ignore newlines until "baseurl:"
  Lycée Technique Industriel Maurice Delafosse (LTID) -(Complexe Delafosses) Électricité,
  Mécanique générale, Maintenance industrielle, Analyses biologiques Au CFA (Centre de 
  Formation Artisanale) du Complexe Delafosse: Ameublement Sculpté, Bijouterie, Cordonnerie
  – Maroquinerie, Coupe – Couture, Poterie – Céramique, Electricité, Mécanique Générale.
banner_image: /uploads/african_students.jpg
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
